# Generated by Django 4.2.7 on 2023-12-03 00:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameArticle', models.CharField(max_length=50)),
                ('categoryArticle', models.TextField()),
                ('descriptionArticle', models.TextField()),
                ('priceArticle', models.IntegerField()),
                ('updatedArticle', models.DateTimeField(blank=True)),
                ('createdArticle', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activeArticle', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stileTattoArtist', models.CharField(max_length=80, null=True)),
                ('experienceArtist', models.IntegerField(null=True)),
                ('nationalityArtist', models.CharField(max_length=80, null=True)),
                ('createdArtist', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updatedArtist', models.DateTimeField(blank=True)),
                ('activeArtist', models.BooleanField(default=True)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeAppointment', models.CharField(max_length=10)),
                ('descriptionAppointment', models.TextField()),
                ('dateAppointment', models.DateTimeField(auto_now_add=True)),
                ('updatedAppointment', models.DateTimeField(blank=True)),
                ('createdAppointment', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('activeAppointment', models.BooleanField(default=True)),
                ('idArtist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.artist')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
