# Generated by Django 5.0 on 2023-12-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_appoinment_createdappointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='experienceArtist',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
