# Generated by Django 5.0 on 2023-12-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_appoinment_idartist_alter_appoinment_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='updatedAppointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
