# Generated by Django 5.0 on 2023-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_appoinment_idartist_alter_appoinment_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imageArticle',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='products/'),
        ),
    ]
