# Generated by Django 4.2.7 on 2023-12-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identificationUser',
            field=models.IntegerField(default=None, unique=True, verbose_name='Identificacion'),
        ),
    ]
